-- Create and use map_db
CREATE DATABASE map_db;
USE map_db;

-- Create Thirteen Tables
CREATE TABLE Y2005 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2006 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2007 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2008 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2009 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2010 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2011 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2012 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2013 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2014 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2015 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2016 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);

CREATE TABLE Y2017 (
  id INT PRIMARY KEY auto_increment,
  `Households; Estimate; Total` INT,
  `Households; Estimate; Total - Less than $10,000` DECIMAL (3, 1),
  `Households; Estimate; Total - $10,000 to $14,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $15,000 to $24,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $25,000 to $34,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $35,000 to $49,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $50,000 to $74,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $75,000 to $99,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $100,000 to $149,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $150,000 to $199,999` DECIMAL (3, 1),
  `Households; Estimate; Total - $200,000 or more` DECIMAL (3, 1),
  `Estimate; White alone` INT,
  `Estimate; Black or African American alone` INT,
  `Estimate; American Indian and Alaska Native alone` INT,
  `Estimate; Asian alone` INT,
  `Estimate; Native Hawaiian and Other Pacific Islander alone` INT,
  `Estimate; Some other race alone` INT,
  `Estimate; Two or more races:` INT,
  `Estimate; Two or more races: - Two races including Some other race` INT,
  `Estimate; Two or more races: - Two races excluding Some other race, and three or more races` INT,
  Geography TEXT,
  `Year` INT,
  Latitude DECIMAL (10, 7),
  Longitude DECIMAL (10, 7),
  `Total; Estimate; Total population` INT,
  `Total; Estimate; AGE - Under 5 years` INT,
  `Total; Estimate; AGE - 5 to 9 years` INT,
  `Total; Estimate; AGE - 10 to 14 years` INT,
  `Total; Estimate; AGE - 15 to 19 years` INT,
  `Total; Estimate; AGE - 20 to 24 years` INT,
  `Total; Estimate; AGE - 25 to 29 years` INT,
  `Total; Estimate; AGE - 30 to 34 years` INT,
  `Total; Estimate; AGE - 35 to 39 years` INT,
  `Total; Estimate; AGE - 40 to 44 years` INT,
  `Total; Estimate; AGE - 45 to 49 years` INT,
  `Total; Estimate; AGE - 50 to 54 years` INT,
  `Total; Estimate; AGE - 55 to 59 years` INT,
  `Total; Estimate; AGE - 60 to 64 years` INT,
  `Total; Estimate; AGE - 65 to 69 years` INT,
  `Total; Estimate; AGE - 70 to 74 years` INT,
  `Total; Estimate; AGE - 80 to 84 years` INT,
  `Total; Estimate; AGE - 85 years and over` INT
);